services:
  grafana:
    user: root
    container_name: 'dartsisas-spice-datasource'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-latest}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      # dist 配下を Grafana の plugins ディレクトリへマウント
      - ./dist:/var/lib/grafana/plugins/dartsisas-spice-datasource
      # （任意）追加の自動プロビジョンを使う場合は samples をコピーした provisioning を利用
      - ./provisioning:/etc/grafana/provisioning
      # ワークスペース全体（ホットリロード開発向け）
      - .:/root/dartsisas-spice-datasource
    environment:
      NODE_ENV: development
      # 以下はデバッグ用。必要時にコメント解除。
      # GF_LOG_FILTERS: plugin.dartsisas-spice-datasource:debug
      # GF_LOG_LEVEL: debug
      # GF_DATAPROXY_LOGGING: 1
      # 未署名プラグインを読み込む許可（開発専用）。署名後は不要。
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: dartsisas-spice-datasource

  web:
    image: nginx:latest
    ports:
      - '3031:80'
    volumes:
      - ./data:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # この nginx はローカルでカーネルファイルを配信するためのサンプル用途。不要なら service ごと削除可。
